# Generated by Django 3.1.7 on 2021-04-05 16:50

import HomeWork.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(choices=[('B', 'Business'), ('M', 'Medicine'), ('I', 'IT')], default='B', max_length=2)),
                ('title', models.CharField(max_length=4096)),
                ('work_text', models.TextField(verbose_name='Work_text')),
                ('home_work_file', models.FileField(upload_to='Home-work/')),
                ('comment', models.TextField(verbose_name='Comments')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Date_published')),
                ('finished_date', models.DateTimeField(verbose_name='Finished_date')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FinishedHomeWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(choices=[('B', 'Business'), ('M', 'Medicine'), ('I', 'IT')], default='B', max_length=2)),
                ('title', models.CharField(default=None, max_length=4096)),
                ('finished_home_work_file', models.FileField(upload_to='Finished-home-work/', validators=[HomeWork.validators.validate_file_size, django.core.validators.FileExtensionValidator(['txt'])])),
                ('created', models.DateTimeField(auto_now=True)),
                ('mark', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Mark')),
                ('comment_of_mark', models.TextField(blank=True, null=True, verbose_name='comment_of_mark')),
                ('home_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeWork.homework', verbose_name='Home_work')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
