# Generated by Django 3.1.7 on 2021-04-23 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeWork', '0002_auto_20210423_2033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('username', 'email', 'password')},
        ),
    ]
