# Generated by Django 3.0.3 on 2021-04-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtheme',
            name='final_date',
            field=models.DateTimeField(default=None),
        ),
    ]
